const QUESTIONS_ADULT = [
  { type: "truth", content: "你的敏感帶在哪裡？", level: "Adult" },
  { type: "truth", content: "第一次發生性行為是在幾歲？", level: "Adult" },
  { type: "truth", content: "最喜歡什麼姿勢？", level: "Adult" },
  {
    type: "truth",
    content: "曾經在戶外或公共場所做過嗎？在哪裡？",
    level: "Adult",
  },
  {
    type: "truth",
    content: "曾經有過性幻想對象是在場的某人嗎？",
    level: "Adult",
  },
  { type: "truth", content: "你喜歡開燈還是關燈？", level: "Adult" },
  { type: "truth", content: "曾經用過交友軟體約砲嗎？", level: "Adult" },
  { type: "truth", content: "一晚最高紀錄幾次？", level: "Adult" },
  {
    type: "truth",
    content: "曾經拍過或被拍過私密照片/影片嗎？",
    level: "Adult",
  },
  {
    type: "truth",
    content: "對於 SM（性虐待/受虐）有興趣嗎？",
    level: "Adult",
  },
  { type: "truth", content: "曾經在車上做過嗎（車震）？", level: "Adult" },
  { type: "truth", content: "喜歡粗暴一點還是溫柔一點？", level: "Adult" },
  { type: "truth", content: "最久一次持續多長時間？", level: "Adult" },
  { type: "truth", content: "曾經假裝高潮過嗎？", level: "Adult" },
  { type: "truth", content: "喜歡在上面還是下面？", level: "Adult" },
  {
    type: "truth",
    content: "曾經跟比自己大/小超過 10 歲的人做過嗎？",
    level: "Adult",
  },
  { type: "truth", content: "你能接受多人運動（3P以上）嗎？", level: "Adult" },
  { type: "truth", content: "曾經在夢裡跟誰做過（春夢）？", level: "Adult" },
  {
    type: "truth",
    content: "對於情趣玩具有什麼看法？擁有過嗎？",
    level: "Adult",
  },
  {
    type: "truth",
    content: "曾經在看電影的時候做過羞羞的事嗎？",
    level: "Adult",
  },
  { type: "truth", content: "喜歡被綁起來還是綁別人？", level: "Adult" },
  { type: "truth", content: "最尷尬的一次性經驗是什麼？", level: "Adult" },
  { type: "truth", content: "曾經在辦公室或學校做過嗎？", level: "Adult" },
  { type: "truth", content: "你看過最奇怪的 A 片類型是什麼？", level: "Adult" },
  {
    type: "truth",
    content: "覺得自己的性能力幾分（滿分10分）？",
    level: "Adult",
  },
  { type: "truth", content: "曾經試過走後門（肛交）嗎？", level: "Adult" },
  { type: "truth", content: "喜歡口交嗎？幫人做或被做？", level: "Adult" },
  { type: "truth", content: "曾經被抓包過正在 DIY 嗎？", level: "Adult" },
  {
    type: "truth",
    content: "有沒有特定制服癖好（護士、老師、警察）？",
    level: "Adult",
  },
  { type: "truth", content: "曾經跟外國人發生過關係嗎？", level: "Adult" },
  { type: "truth", content: "能接受不戴套嗎？", level: "Adult" },
  { type: "truth", content: "曾經在做愛時睡著嗎？", level: "Adult" },
  { type: "truth", content: "喜歡對方發出聲音還是安靜？", level: "Adult" },
  { type: "truth", content: "最喜歡對方親吻你哪裡？", level: "Adult" },
  { type: "truth", content: "曾經在海邊或水裡做過嗎？", level: "Adult" },
  { type: "truth", content: "覺得尺寸（長度/大小）重要嗎？", level: "Adult" },
  { type: "truth", content: "曾經跟同性發生過邊緣性行為嗎？", level: "Adult" },
  {
    type: "truth",
    content: "你最想嘗試的一個性幻想場景是什麼？",
    level: "Adult",
  },
  {
    type: "truth",
    content: "曾經做愛到受傷送醫或需要擦藥嗎？",
    level: "Adult",
  },
  { type: "truth", content: "喜歡咬人或被咬嗎？", level: "Adult" },
  { type: "truth", content: "曾經因為性事不合而分手嗎？", level: "Adult" },
  { type: "truth", content: "能夠接受開放式關係嗎？", level: "Adult" },
  {
    type: "truth",
    content: "曾經在電話裡做愛（Phone Sex）嗎？",
    level: "Adult",
  },
  {
    type: "truth",
    content: "你覺得在場誰的性技巧看起來最好？",
    level: "Adult",
  },
  { type: "truth", content: "曾經吞下過對方的體液嗎？", level: "Adult" },
  { type: "truth", content: "喜歡在鏡子面前做嗎？", level: "Adult" },
  { type: "truth", content: "曾經跟好朋友的兄弟姊妹做過嗎？", level: "Adult" },
  { type: "truth", content: "一周通常需要幾次？", level: "Adult" },
  {
    type: "truth",
    content: "曾經因為太興奮而秒射（或極快結束）嗎？",
    level: "Adult",
  },
  { type: "truth", content: "現在穿的內衣/內褲是什麼顏色？", level: "Adult" },
  {
    type: "truth",
    content: "在場的異性中，誰最接近你的性幻想對象？",
    level: "Adult",
  },
  {
    type: "truth",
    content: "曾經有過一夜情嗎？或者想嘗試嗎？",
    level: "Adult",
  },
  { type: "truth", content: "能夠接受的年齡差最大是多少？", level: "Adult" },
  { type: "truth", content: "最喜歡身體哪個部位被觸摸？", level: "Adult" },
  {
    type: "truth",
    content: "曾經有過性幻想對象是老師或上司嗎？",
    level: "Adult",
  },
  { type: "truth", content: "曾經玩過角色扮演嗎？", level: "Adult" },
  { type: "truth", content: "覺得性愛中最重要的環節是什麼？", level: "Adult" },
  { type: "truth", content: "最近一次DIY是什麼時候？", level: "Adult" },
  { type: "truth", content: "覺得性重要還是愛重要？", level: "Adult" },
  { type: "truth", content: "喜歡被控制還是控制對方？", level: "Adult" },
  { type: "truth", content: "最喜歡的愛愛時間長度？", level: "Adult" },
  { type: "truth", content: "喜歡穿丁字褲嗎？", level: "Adult" },
  { type: "dare", content: "親吻你左邊玩家的脖子。", level: "Adult" },
  {
    type: "dare",
    content: "選一位異性，用嘴對嘴傳遞一張衛生紙（或冰塊）。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "在在場異性中選一位，在他耳邊吹氣並說悄悄話。",
    level: "Adult",
  },
  { type: "dare", content: "讓一位異性坐在你大腿上 1 分鐘。", level: "Adult" },
  {
    type: "dare",
    content: "對著一位異性做出挑逗的吃香蕉（或手指）動作。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "打給一個異性朋友問他要不要跟你去開房間（然後說是玩遊戲）。",
    level: "Adult",
  },
  { type: "dare", content: "在一位異性身上做伏地挺身 5 下。", level: "Adult" },
  { type: "dare", content: "讓某人咬你的耳朵一下。", level: "Adult" },
  { type: "dare", content: "用嘴巴幫異性擦護唇膏。", level: "Adult" },
  {
    type: "dare",
    content: "把內衣/內褲脫掉送給在場的一個人（如果環境允許）。",
    level: "Adult",
  },
  { type: "dare", content: "大聲朗讀一段情色小說的段落。", level: "Adult" },
  {
    type: "dare",
    content: "讓右邊的人在你脖子上種草莓（或假裝用力吸一下）。",
    level: "Adult",
  },
  { type: "dare", content: "發出呻吟聲10秒。", level: "Adult" },
  { type: "dare", content: "對著在場一位異性做出挑逗動作。", level: "Adult" },
  { type: "dare", content: "讓在場一位異性摸你的大腿內側。", level: "Adult" },
  { type: "dare", content: "模仿一種性愛姿勢（對著空氣）。", level: "Adult" },
  { type: "dare", content: "脫掉一件衣服（外套或配件）。", level: "Adult" },
  { type: "dare", content: "親吻在場一位異性的耳朵。", level: "Adult" },
  {
    type: "dare",
    content: "讓在場一位異性坐在你身上做伏地挺身。",
    level: "Adult",
  },
  { type: "dare", content: "用嘴巴解開在場一位異性的扣子。", level: "Adult" },
  {
    type: "dare",
    content: "隔著衣服撫摸在場一位異性的胸部/腹肌。",
    level: "Adult",
  },
  { type: "dare", content: "說一句你覺得最色的話。", level: "Adult" },
  { type: "dare", content: "對著異性做頂胯動作10下。", level: "Adult" },
  { type: "dare", content: "讓異性摸你的腹肌/肚子。", level: "Adult" },
  { type: "dare", content: "親吻異性的鎖骨。", level: "Adult" },
  { type: "dare", content: "隔著衣服親吻異性的胸口。", level: "Adult" },
  { type: "dare", content: "讓異性幫你脫襪子。", level: "Adult" },
  { type: "dare", content: "用嘴巴餵異性吃東西。", level: "Adult" },
  { type: "dare", content: "躺在地上讓異性跨過去。", level: "Adult" },
  { type: "dare", content: "握住異性的手放在自己胸口。", level: "Adult" },
  { type: "dare", content: "跟異性磨鼻子10秒。", level: "Adult" },
  { type: "dare", content: "用很色的語氣說「我要吃掉你」。", level: "Adult" },
  { type: "dare", content: "對著異性跳M字腿。", level: "Adult" },
  { type: "dare", content: "含著冰塊親吻異性的手。", level: "Adult" },
  { type: "dare", content: "讓異性聞你的脖子。", level: "Adult" },
  { type: "dare", content: "用領帶或皮帶輕輕綁住異性的手。", level: "Adult" },
  {
    type: "dare",
    content: "讓某人把手伸進你的褲子裡（只摸大腿內側）。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "跟在場的一個人舌吻 5 秒（如果雙方同意）。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "用嘴巴把冰塊在某人的脖子和胸口滑動。",
    level: "Adult",
  },
  { type: "dare", content: "讓在場的異性坐在你身上搖 10 下。", level: "Adult" },
  { type: "dare", content: "讓某人咬你的鎖骨留下草莓。", level: "Adult" },
  {
    type: "dare",
    content: "隔著褲子/裙子撫摸自己的私密處 10 秒。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "讓坐在右邊的人解開你的內衣扣子（女生）或解開皮帶（男生）。",
    level: "Adult",
  },
  { type: "dare", content: "親吻在場異性的大腿內側。", level: "Adult" },
  { type: "dare", content: "用嘴巴脫掉某人的襪子。", level: "Adult" },
  {
    type: "dare",
    content: "讓某人在你耳朵旁邊吹氣並發出呻吟聲。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "被矇住眼睛，讓某人用身體的一個部位碰你的臉，你要猜是什麼。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "兩人一組，用身體擠爆一顆氣球（不能用手）。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "讓某人在你的胸口（或腹肌）上倒酒並喝掉。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "讓異性把手放在你的心臟位置（胸部）10 秒。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "舔掉塗在某人身上的鮮奶油（或果醬）。",
    level: "Adult",
  },
  { type: "dare", content: "用性感的聲音叫出在場某人的名字。", level: "Adult" },
  {
    type: "dare",
    content: "讓異性坐在你的臉上（不用真的坐下去，借位）。",
    level: "Adult",
  },
  { type: "dare", content: "親吻某人的乳溝（或胸肌）。", level: "Adult" },
  { type: "dare", content: "用大腿夾住某人的腰。", level: "Adult" },
  {
    type: "dare",
    content: "讓某人用手指在你的大腿上寫字，你要猜出來。",
    level: "Adult",
  },
  { type: "dare", content: "兩人共吃一條餅乾直到嘴對嘴。", level: "Adult" },
  {
    type: "dare",
    content: "讓某人把手伸進你的衣服，按摩你的背。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "跪在地上，抬頭看著異性說「主人請處罰我」。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "脫掉上衣（男生）或展現事業線（女生）。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "讓某人從背後抱住你，並聞你的頭髮。",
    level: "Adult",
  },
  { type: "dare", content: "讓在場的人指定你親吻某個部位。", level: "Adult" },
  { type: "dare", content: "用胸部去磨蹭某人的手臂。", level: "Adult" },
  {
    type: "dare",
    content: "躺在某人的大腿上，讓他幫你掏耳朵。",
    level: "Adult",
  },
  { type: "dare", content: "對著某人的耳朵輕聲說「我想要」。", level: "Adult" },
  { type: "dare", content: "讓異性幫你脫掉一件衣服。", level: "Adult" },
  {
    type: "dare",
    content: "模擬口交的動作（對著香蕉或瓶子）。",
    level: "Adult",
  },
  { type: "dare", content: "讓大家看到你的內褲邊緣。", level: "Adult" },
  {
    type: "dare",
    content:
      "跟某人十指緊扣並深情對望，直到有人硬了或濕了（開玩笑的，直到笑場）。",
    level: "Adult",
  },
  { type: "dare", content: "讓某人用舌頭舔你的脖子。", level: "Adult" },
  { type: "dare", content: "把手放在異性的大腿根部 1分鐘。", level: "Adult" },
  {
    type: "dare",
    content: "跟在場的一個人去廁所待 3 分鐘（什麼都不做也可以）。",
    level: "Adult",
  },
];
