const QUESTIONS_HARD = [
  { type: "truth", content: "在場你最不喜歡誰？（必須講一個）", level: "Hard" },
  { type: "truth", content: "你曾經背叛過在場的任何一個人嗎？", level: "Hard" },
  {
    type: "truth",
    content: "如果必須殺掉在場一個人才能活下去，你選誰？",
    level: "Hard",
  },
  {
    type: "truth",
    content: "你最近一次說謊是什麼時候？內容是什麼？",
    level: "Hard",
  },
  { type: "truth", content: "曾經希望哪個朋友從這世界上消失？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰最虛偽？", level: "Hard" },
  {
    type: "truth",
    content: "講出一個你從未告訴過別人的深層秘密。",
    level: "Hard",
  },
  { type: "truth", content: "你曾經在心裡詛咒過父母嗎？", level: "Hard" },
  { type: "truth", content: "你人生中最後悔的一件事是什麼？", level: "Hard" },
  {
    type: "truth",
    content: "如果給你一千萬，要你跟在場最醜的人結婚，你願意嗎？",
    level: "Hard",
  },
  {
    type: "truth",
    content: "曾經做過犯法的事嗎（包含微小的違規）？",
    level: "Hard",
  },
  { type: "truth", content: "你覺得自己配得上現在的伴侶嗎？", level: "Hard" },
  { type: "truth", content: "曾經懷疑過自己的性向嗎？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰的智商最低？", level: "Hard" },
  {
    type: "truth",
    content: "曾經利用過朋友來達到自己的目的嗎？",
    level: "Hard",
  },
  { type: "truth", content: "上一次嫉妒別人是什麼時候？", level: "Hard" },
  { type: "truth", content: "你覺得自己是一個好人嗎？為什麼？", level: "Hard" },
  { type: "truth", content: "曾經偷吃（精神或肉體出軌）過嗎？", level: "Hard" },
  {
    type: "truth",
    content: "如果你的好友殺了人，你會幫他藏屍體還是報警？",
    level: "Hard",
  },
  { type: "truth", content: "在場誰的穿衣品味你最看不懂？", level: "Hard" },
  { type: "truth", content: "你曾經跟朋友的另一半有過曖昧嗎？", level: "Hard" },
  {
    type: "truth",
    content: "講出一個前任最讓你受不了的缺點（要指名道姓）。",
    level: "Hard",
  },
  { type: "truth", content: "你覺得在場誰最容易出軌？", level: "Hard" },
  { type: "truth", content: "你曾經在背後說過在場誰的壞話？", level: "Hard" },
  { type: "truth", content: "為了錢，你願意出賣什麼底線？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰過得最失敗？", level: "Hard" },
  { type: "truth", content: "曾經希望自己的兄弟姊妹不存在嗎？", level: "Hard" },
  { type: "truth", content: "你最看不起哪一種人？", level: "Hard" },
  { type: "truth", content: "曾經對老師或長輩有過非分之想嗎？", level: "Hard" },
  {
    type: "truth",
    content: "如果你可以刪除一段記憶，你會刪除哪一段？",
    level: "Hard",
  },
  { type: "truth", content: "你覺得在場誰最沒異性緣？", level: "Hard" },
  { type: "truth", content: "曾經在心裡嘲笑過在場的人嗎？", level: "Hard" },
  { type: "truth", content: "你覺得自己這輩子最對不起誰？", level: "Hard" },
  { type: "truth", content: "為了活命，你會願意吃人肉嗎？", level: "Hard" },
  { type: "truth", content: "曾經想過要自殺嗎？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰最難相處？", level: "Hard" },
  {
    type: "truth",
    content: "如果你的伴侶變植物人，你會照顧他一輩子還是離開？",
    level: "Hard",
  },
  { type: "truth", content: "曾經偷看過父母親熱嗎？", level: "Hard" },
  {
    type: "truth",
    content: "你覺得自己最大的性幻想對象是誰（不限名人）？",
    level: "Hard",
  },
  { type: "truth", content: "曾經故意破壞別人的感情嗎？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰最愛裝模作樣？", level: "Hard" },
  {
    type: "truth",
    content: "講出一個你覺得在場某人該改進的缺點。",
    level: "Hard",
  },
  { type: "truth", content: "你曾經把別人的秘密洩漏出去嗎？", level: "Hard" },
  {
    type: "truth",
    content: "你覺得你的前任現在過得好不好？你會開心嗎？",
    level: "Hard",
  },
  { type: "truth", content: "曾經因為嫉妒而故意陷害別人嗎？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰最不可能成功？", level: "Hard" },
  { type: "truth", content: "你現在心裡最想對誰說「對不起」？", level: "Hard" },
  { type: "truth", content: "曾經對好朋友產生過性幻想嗎？", level: "Hard" },
  {
    type: "truth",
    content: "講出一個你絕對不會讓父母知道的秘密。",
    level: "Hard",
  },
  {
    type: "truth",
    content: "如果現在要你跟現場一個人絕交，你會選誰？",
    level: "Hard",
  },
  { type: "truth", content: "說出你做過最違法的事情。", level: "Hard" },
  {
    type: "truth",
    content: "如果生命只剩24小時，想對誰說什麼？",
    level: "Hard",
  },
  {
    type: "truth",
    content: "成長過程中，哪件事對你的價值觀影響最大？",
    level: "Hard",
  },
  { type: "truth", content: "你最害怕失去什麼？", level: "Hard" },
  { type: "truth", content: "曾經對朋友的另一半動過心嗎？", level: "Hard" },
  { type: "truth", content: "上一次發自內心大哭是什麼時候？", level: "Hard" },
  { type: "truth", content: "有沒有哪個夢想是你已經放棄的？", level: "Hard" },
  { type: "truth", content: "曾經背叛過好朋友嗎？", level: "Hard" },
  { type: "truth", content: "曾經偷過東西嗎（不論大小）？", level: "Hard" },
  { type: "truth", content: "對在場誰的第一印象最差？", level: "Hard" },
  { type: "truth", content: "曾經想過要整型嗎？想整哪裡？", level: "Hard" },
  { type: "truth", content: "覺得自己人生中最失敗的一件事？", level: "Hard" },
  { type: "truth", content: "曾經腳踏兩條船嗎？", level: "Hard" },
  {
    type: "truth",
    content: "討厭在場某人的某個行為嗎？請誠實。",
    level: "Hard",
  },
  { type: "truth", content: "曾經偷看過另一半的手機訊息嗎？", level: "Hard" },
  { type: "truth", content: "曾經後悔跟某任交往嗎？", level: "Hard" },
  { type: "truth", content: "曾經為了利益出賣過朋友嗎？", level: "Hard" },
  { type: "truth", content: "說出一個你最想刪除的黑歷史。", level: "Hard" },
  {
    type: "truth",
    content: "如果一定要跟在場一個人接吻，你會選誰？",
    level: "Hard",
  },
  { type: "truth", content: "曾經在心裡偷偷詛咒過誰？", level: "Hard" },
  { type: "truth", content: "曾經跟不喜歡的人交往過嗎？", level: "Hard" },
  { type: "truth", content: "曾經為了愛做過最傻的事？", level: "Hard" },
  { type: "truth", content: "有沒有當過第三者（或被當過）？", level: "Hard" },
  {
    type: "truth",
    content: "如果世界末日，只能救一個人，救誰？",
    level: "Hard",
  },
  { type: "truth", content: "最想跟誰道歉？", level: "Hard" },
  { type: "truth", content: "最害怕的一種死法？", level: "Hard" },
  { type: "truth", content: "曾有過「一夜情」的念頭嗎？", level: "Hard" },
  {
    type: "dare",
    content: "用你的鼻子碰在場任何一個人的手掌。",
    level: "Hard",
  },
  { type: "dare", content: "用屁股撞在場每個人的屁股一下。", level: "Hard" },
  {
    type: "dare",
    content: "打給媽媽說：「我好像喜歡上同性了」（記得解釋）。",
    level: "Hard",
  },
  { type: "dare", content: "親吻右邊人的手背。", level: "Hard" },
  { type: "dare", content: "聞右邊人的襪子。", level: "Hard" },
  { type: "dare", content: "跟在場的一位異性借位接吻拍照。", level: "Hard" },
  { type: "dare", content: "讓坐在你右邊的人聞你的腳。", level: "Hard" },
  {
    type: "dare",
    content: "用嘴巴咬下別人的襪子（不用真的咬到肉）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "讓大家傳一則惡作劇訊息給你的父母。",
    level: "Hard",
  },
  { type: "dare", content: "模仿高潮的表情並自拍。", level: "Hard" },
  { type: "dare", content: "讓坐在左邊的人坐在你腿上一輪。", level: "Hard" },
  { type: "dare", content: "把內褲穿在褲子外面一輪。", level: "Hard" },
  {
    type: "dare",
    content: "去便利商店買一包保險套（如果你敢的話）。",
    level: "Hard",
  },
  { type: "dare", content: "把頭埋在某人的懷裡 10 秒。", level: "Hard" },
  { type: "dare", content: "模仿一種動物交配的聲音。", level: "Hard" },
  { type: "dare", content: "讓某人打你的屁股一下。", level: "Hard" },
  { type: "dare", content: "用嘴巴解開某人的鞋帶。", level: "Hard" },
  {
    type: "dare",
    content: "傳訊息給老闆或老師說「我想你了」。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "去冰箱拿一顆冰塊，放在衣服裡直到融化。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "讓大家看你手機相簿裡最新的那張截圖。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "跟大家分享你內褲的顏色和款式（必須檢查）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "擁抱在你右邊的人 20 秒，什麼話都不能說。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "打電話給一位好久沒聯絡的朋友，說想他了。",
    level: "Hard",
  },
  { type: "dare", content: "選一個人，幫他按摩 3 分鐘。", level: "Hard" },
  {
    type: "dare",
    content: "在社群媒體上發一篇感謝文，感謝在場的一個人。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "打電話給前任（或隨機異性朋友）說「我好想你」。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "隨機挑選通訊錄的一個人，傳送「我懷孕了/我讓別人懷孕了」。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "模仿一種猥瑣的表情自拍並發到群組。",
    level: "Hard",
  },
  { type: "dare", content: "讓右邊的人聞你的腋下。", level: "Hard" },
  { type: "dare", content: "喝一杯特調飲料（大家隨意加料）。", level: "Hard" },
  { type: "dare", content: "大聲喊出自己最丟臉的綽號。", level: "Hard" },
  { type: "dare", content: "公主抱在場一位異性。", level: "Hard" },
  { type: "dare", content: "用嘴巴咬下左邊人身上的便利貼。", level: "Hard" },
  { type: "dare", content: "喝一杯加了鹽的可樂。", level: "Hard" },
  { type: "dare", content: "讓右邊的人坐在你背上做伏地挺身。", level: "Hard" },
  { type: "dare", content: "把頭像換成鬼臉照一天。", level: "Hard" },
  {
    type: "dare",
    content: "傳訊息給第10個聯絡人說「借我錢」。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "在社群媒體發一張醜照，標註「我覺得自己好美」，一小時不准刪。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "出門搭訕一個路人，並要到他的 Line/IG。",
    level: "Hard",
  },
  { type: "dare", content: "生吃一顆大蒜或一匙芥末。", level: "Hard" },
  {
    type: "dare",
    content: "打給前任，問他「你有愛過我嗎」。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "讓一個人用膠帶貼你的腿毛（或手毛）並撕下來。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "把頭伸進馬桶裡（乾淨的）自拍一張。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "用嘴巴傳遞冰塊給下一個人（不用真的碰到嘴）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "讓大家把你綁起來（用膠帶或繩子）5 分鐘。",
    level: "Hard",
  },
  { type: "dare", content: "舔地板一下（或桌子）。", level: "Hard" },
  { type: "dare", content: "去隔壁桌（或是鄰居）借衛生紙。", level: "Hard" },
  {
    type: "dare",
    content: "讓大家看你手機裡最私密的一張照片（不准拒絕）。",
    level: "Hard",
  },
  { type: "dare", content: "站在椅子上大聲唱國歌。", level: "Hard" },
  { type: "dare", content: "把臉埋進麵粉堆裡。", level: "Hard" },
  { type: "dare", content: "隨機按電鈴並跑掉（請注意安全）。", level: "Hard" },
  { type: "dare", content: "用舌頭舔某人的手肘。", level: "Hard" },
  {
    type: "dare",
    content: "傳訊息跟喜歡的人告白（不能說是遊戲）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "喝掉一瓶養樂多（或水）不能吞嚥，含在嘴裡 1 分鐘。",
    level: "Hard",
  },
  { type: "dare", content: "模仿發情的狗抱著某人的腿。", level: "Hard" },
  { type: "dare", content: "生吃一片檸檬（連皮）。", level: "Hard" },

  { type: "dare", content: "在路邊對著車子揮手像在選美。", level: "Hard" },
  { type: "dare", content: "讓大家把你的眉毛畫成一直線。", level: "Hard" },
  { type: "dare", content: "隨機攔截路人，請他幫你拍照。", level: "Hard" },
  { type: "dare", content: "穿著內褲（或泳衣）跑一圈。", level: "Hard" },
  { type: "dare", content: "去超商對店員說「歡迎光臨」。", level: "Hard" },
  { type: "dare", content: "讓大家把所有零錢倒在你身上。", level: "Hard" },
  { type: "dare", content: "模仿正在生孩子的孕婦。", level: "Hard" },
  {
    type: "dare",
    content: "用舌頭把櫻桃梗打結（或試圖做這動作）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "讓某人把生雞蛋打在你頭上（如果有準備）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "把手機交給在場最調皮的人保管 10 分鐘。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "去問路人「請問我的臉上有東西嗎？」。",
    level: "Hard",
  },
  { type: "dare", content: "喝一口醬油。", level: "Hard" },
];
