const QUESTIONS_EASY = [
  {
    type: "truth",
    content: "你的手機桌布是什麼？為什麼選這張？",
    level: "Easy",
  },
  { type: "truth", content: "如果中樂透頭獎，第一件事做什麼？", level: "Easy" },
  {
    type: "truth",
    content: "你睡覺有什麼怪癖？（打呼、流口水、抱被子...）",
    level: "Easy",
  },
  { type: "truth", content: "最近一次哭是因為什麼？", level: "Easy" },
  { type: "truth", content: "覺得自己像哪種動物？", level: "Easy" },
  { type: "truth", content: "你最怕哪種昆蟲或動物？", level: "Easy" },
  { type: "truth", content: "如果能有超能力，你想要什麼？", level: "Easy" },
  { type: "truth", content: "小時候的夢想職業是什麼？", level: "Easy" },
  { type: "truth", content: "去KTV必點的一首歌是？", level: "Easy" },
  { type: "truth", content: "洗澡時會做的最奇怪的一件事？", level: "Easy" },
  { type: "truth", content: "身上哪個部位最滿意？", level: "Easy" },
  { type: "truth", content: "說出一個你絕對不敢吃的食物。", level: "Easy" },
  { type: "truth", content: "你覺得在場誰最自戀？", level: "Easy" },
  { type: "truth", content: "上一次尿床是幾歲？", level: "Easy" },
  { type: "truth", content: "買過最後悔的東西是什麼？", level: "Easy" },
  { type: "truth", content: "如果明天是世界末日，你會吃什麼？", level: "Easy" },
  { type: "truth", content: "你相信這世上有鬼嗎？", level: "Easy" },
  { type: "truth", content: "做過最奇怪的夢是什麼？", level: "Easy" },
  { type: "truth", content: "你的拿手菜是什麼？（泡麵也算）", level: "Easy" },
  { type: "truth", content: "最喜歡的一部電影是？", level: "Easy" },
  { type: "truth", content: "覺得自己心理年齡幾歲？", level: "Easy" },
  {
    type: "truth",
    content: "如果可以跟在場一人交換身份一天，想選誰？",
    level: "Easy",
  },
  { type: "truth", content: "說出一件你小時候做過的蠢事。", level: "Easy" },
  { type: "truth", content: "你有多少天沒洗頭的最高紀錄？", level: "Easy" },
  { type: "truth", content: "覺得在場誰看起來脾氣最好？", level: "Easy" },
  { type: "truth", content: "最喜歡的季節是哪個？為什麼？", level: "Easy" },
  { type: "truth", content: "你比較喜歡貓還是狗？", level: "Easy" },
  { type: "truth", content: "早餐通常都吃什麼？", level: "Easy" },
  { type: "truth", content: "最近看的一本書或漫畫是什麼？", level: "Easy" },
  { type: "truth", content: "你最喜歡的顏色是什麼？", level: "Easy" },
  { type: "truth", content: "你相信星座或算命嗎？", level: "Easy" },
  { type: "truth", content: "喜歡喝咖啡還是茶？", level: "Easy" },
  { type: "truth", content: "如果可以出國，現在最想去哪裡？", level: "Easy" },
  { type: "truth", content: "假日通常喜歡做什麼休閒活動？", level: "Easy" },
  { type: "truth", content: "有沒有收集什麼特別的東西？", level: "Easy" },
  { type: "truth", content: "最喜歡的水果是什麼？", level: "Easy" },
  { type: "truth", content: "喜歡爬山還是去海邊？", level: "Easy" },
  { type: "truth", content: "敢不敢吃榴槤或臭豆腐？", level: "Easy" },
  { type: "truth", content: "平時喜歡聽什麼類型的音樂？", level: "Easy" },
  { type: "truth", content: "最近一次去便利商店買了什麼？", level: "Easy" },
  { type: "truth", content: "上廁所完會看一眼排泄物嗎？", level: "Easy" },
  { type: "truth", content: "洗澡會順便尿尿嗎？", level: "Easy" },
  { type: "truth", content: "如果變成異性，第一件事想做什麼？", level: "Easy" },
  { type: "truth", content: "曾經裸睡過嗎？", level: "Easy" },
  { type: "truth", content: "覺得自己聰明嗎？", level: "Easy" },
  { type: "truth", content: "最喜歡的一道菜？", level: "Easy" },
  { type: "dare", content: "模仿一種動物直到下一輪。", level: "Easy" },
  { type: "dare", content: "做鬼臉自拍一張。", level: "Easy" },
  { type: "dare", content: "模仿一種動物的叫聲。", level: "Easy" },
  { type: "dare", content: "對著窗外大喊：「我是笨蛋！」", level: "Easy" },
  { type: "dare", content: "原地轉 10 圈，然後走直線。", level: "Easy" },
  { type: "dare", content: "讓大家看你手機裡第 5 張照片。", level: "Easy" },
  { type: "dare", content: "用「喵」代替「我」說話三分鐘。", level: "Easy" },
  { type: "dare", content: "模仿在場某個人的口頭禪。", level: "Easy" },
  { type: "dare", content: "誇獎右邊的人三個優點。", level: "Easy" },
  { type: "dare", content: "唱一首兒歌（例如兩隻老虎）。", level: "Easy" },
  { type: "dare", content: "用屁股寫字（你的名字）。", level: "Easy" },
  { type: "dare", content: "讓左邊的人幫你整理頭髮。", level: "Easy" },
  { type: "dare", content: "雙手舉高維持一分鐘。", level: "Easy" },
  { type: "dare", content: "和右邊的人十指緊扣 10 秒。", level: "Easy" },
  { type: "dare", content: "模仿名模走台步一圈。", level: "Easy" },
  { type: "dare", content: "講一個冷笑話。", level: "Easy" },
  { type: "dare", content: "跟大家分享你最近的一個搜尋紀錄。", level: "Easy" },
  { type: "dare", content: "對著鏡子稱讚自己 30 秒。", level: "Easy" },
  { type: "dare", content: "學嬰兒哭 10 秒。", level: "Easy" },
  { type: "dare", content: "喝一大杯水。", level: "Easy" },
  { type: "dare", content: "讓大家檢查你的包包。", level: "Easy" },
  { type: "dare", content: "做一個最醜的鬼臉。", level: "Easy" },
  { type: "dare", content: "模仿貓叫三聲「喵喵喵」。", level: "Easy" },
  { type: "dare", content: "站起來原地轉一圈。", level: "Easy" },
  { type: "dare", content: "跟左邊的人擊掌。", level: "Easy" },
  { type: "dare", content: "說一個笑話（不好笑也要笑）。", level: "Easy" },
  { type: "dare", content: "閉眼單腳站立5秒。", level: "Easy" },
  { type: "dare", content: "模仿機器人說話一句。", level: "Easy" },
  { type: "dare", content: "對著空氣揮手說「嗨」。", level: "Easy" },
  { type: "dare", content: "做出一個驚訝的表情維持5秒。", level: "Easy" },
  { type: "dare", content: "模仿一種樂器的聲音。", level: "Easy" },
  { type: "dare", content: "模仿一種動物的求偶舞。", level: "Easy" },
  { type: "dare", content: "用屁股寫「我愛你」。", level: "Easy" },
  { type: "dare", content: "對著窗外大喊「我是大笨蛋」。", level: "Easy" },
  { type: "dare", content: "模仿在場一個人的說話方式。", level: "Easy" },
  { type: "dare", content: "對著鏡子猜拳直到贏為止。", level: "Easy" },
  { type: "dare", content: "讓在場的人幫你綁頭髮（或弄亂）。", level: "Easy" },
  { type: "dare", content: "跟牆壁深情告白30秒。", level: "Easy" },
  { type: "dare", content: "模仿便秘時的表情。", level: "Easy" },
  { type: "dare", content: "用舌頭舔手肘（舔不到也要試）。", level: "Easy" },
];
