const QUESTIONS_NORMAL = [
  { type: "truth", content: "曾經假裝生病請假去做什麼？", level: "Normal" },
  { type: "truth", content: "覺得在場誰的衣品最差？", level: "Normal" },
  {
    type: "truth",
    content: "手機裡最醜的一張照片是誰？（必須展示）",
    level: "Normal",
  },
  { type: "truth", content: "曾經偷看過誰的手機或日記？", level: "Normal" },
  { type: "truth", content: "說出你在場最想吐槽的一個人。", level: "Normal" },
  {
    type: "truth",
    content: "在場這群人中，你覺得誰將來會最富有？",
    level: "Normal",
  },
  { type: "truth", content: "曾經在游泳池偷尿尿過嗎？", level: "Normal" },
  {
    type: "truth",
    content: "上一次放屁不小心崩出「東西」是什麼時候？",
    level: "Normal",
  },
  {
    type: "truth",
    content: "如果你是異性，你會想跟自己交往嗎？",
    level: "Normal",
  },
  { type: "truth", content: "曾經把別人送的禮物轉送出去嗎？", level: "Normal" },
  { type: "truth", content: "覺得在場誰最容易被詐騙？", level: "Normal" },
  {
    type: "truth",
    content: "說出一個你不想讓父母知道的秘密。",
    level: "Normal",
  },
  { type: "truth", content: "曾經在公共場合做過最丟臉的事？", level: "Normal" },
  { type: "truth", content: "覺得哪個卡通人物最性感？", level: "Normal" },
  {
    type: "truth",
    content: "如果要刪除一位在場好友的聯絡方式，選誰？",
    level: "Normal",
  },
  { type: "truth", content: "曾經對老闆或老師說過最大的謊？", level: "Normal" },
  { type: "truth", content: "洗衣服會把內褲跟襪子一起洗嗎？", level: "Normal" },
  { type: "truth", content: "曾經偷吃過別人的東西沒承認嗎？", level: "Normal" },
  { type: "truth", content: "覺得在場誰最會記仇？", level: "Normal" },
  { type: "truth", content: "有沒有挖鼻孔吃下去過？", level: "Normal" },
  { type: "truth", content: "學生時代曾經作弊過嗎？", level: "Normal" },
  { type: "truth", content: "上一次生氣是因為什麼事情？", level: "Normal" },
  { type: "truth", content: "覺得自己最大的優點是什麼？", level: "Normal" },
  { type: "truth", content: "覺得自己最大的缺點是什麼？", level: "Normal" },
  { type: "truth", content: "曾經對好朋友說過謊嗎？", level: "Normal" },
  { type: "truth", content: "有沒有暗戀過老師或長輩？", level: "Normal" },
  { type: "truth", content: "第一次約會去了哪裡？", level: "Normal" },
  { type: "truth", content: "最討厭的一種食物是什麼？", level: "Normal" },
  {
    type: "truth",
    content: "曾經在電影院看電影看到睡著過嗎？",
    level: "Normal",
  },
  { type: "truth", content: "敢不敢一個人看恐怖片？", level: "Normal" },
  { type: "truth", content: "曾經迷路過最久的一次是多久？", level: "Normal" },
  { type: "truth", content: "小時候最怕什麼東西？", level: "Normal" },
  {
    type: "truth",
    content: "曾經不小心把別人的秘密說出去嗎？",
    level: "Normal",
  },
  { type: "truth", content: "覺得在場誰最幽默好笑？", level: "Normal" },
  { type: "truth", content: "如果能回到過去，最想回到幾歲？", level: "Normal" },
  { type: "truth", content: "如果可以整型，你最想整哪裡？", level: "Normal" },
  {
    type: "truth",
    content: "你覺得在場誰最適合當你的另一半？",
    level: "Normal",
  },
  { type: "truth", content: "有沒有欠錢不還過？", level: "Normal" },
  { type: "truth", content: "最想刪除的一張照片是什麼？", level: "Normal" },
  { type: "truth", content: "說出一個你討厭的藝人。", level: "Normal" },
  { type: "truth", content: "覺得在場誰最愛記仇？", level: "Normal" },
  { type: "truth", content: "初吻是在幾歲？", level: "Normal" },
  { type: "truth", content: "最尷尬的一次約會經驗？", level: "Normal" },
  { type: "truth", content: "有沒有被同性告白過？", level: "Normal" },
  { type: "truth", content: "覺得自己哪個部位最性感？", level: "Normal" },
  {
    type: "truth",
    content: "如果中了一億，會分給在場的人嗎？",
    level: "Normal",
  },
  { type: "truth", content: "最受不了異性哪個行為？", level: "Normal" },
  { type: "truth", content: "曾經在夢裡夢過在場的人嗎？", level: "Normal" },
  { type: "truth", content: "有沒有說過謊來逃避聚會？", level: "Normal" },
  { type: "truth", content: "最近一個搜尋的關鍵字是什麼？", level: "Normal" },
  { type: "truth", content: "有沒有什麼怪癖？", level: "Normal" },
  { type: "truth", content: "曾經被警察攔下來過嗎？", level: "Normal" },
  { type: "truth", content: "覺得在場誰最單純？", level: "Normal" },
  { type: "truth", content: "曾經偷拿過家裡的錢嗎？", level: "Normal" },
  { type: "truth", content: "覺得自己的顏值幾分？", level: "Normal" },
  {
    type: "dare",
    content: "隨機打給通訊錄一個人唱生日快樂歌。",
    level: "Normal",
  },
  { type: "dare", content: "用屁股撞在場每個人的屁股一下。", level: "Normal" },
  { type: "dare", content: "含著水哼一首歌讓大家猜。", level: "Normal" },
  { type: "dare", content: "跳一段目前最紅的抖音舞。", level: "Normal" },
  {
    type: "dare",
    content: "讓右邊的人搔你癢 10 秒鐘，不能笑。",
    level: "Normal",
  },
  { type: "dare", content: "用你的手肘打字發一則動態。", level: "Normal" },
  { type: "dare", content: "跪在椅子上模仿古代人請安。", level: "Normal" },
  { type: "dare", content: "夾著鼻子說話一輪。", level: "Normal" },
  {
    type: "dare",
    content: "把鞋子脫下來，聞一下並形容味道。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "去廚房特調一杯「怪味飲料」並喝一口。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "打給媽媽說：「我好像喜歡上同性了」（記得解釋）。",
    level: "Normal",
  },
  { type: "dare", content: "讓在場每個人彈你額頭一下。", level: "Normal" },
  { type: "dare", content: "假裝電視購物推銷你穿的襪子。", level: "Normal" },
  { type: "dare", content: "對著Siri大喊「我好寂寞」。", level: "Normal" },
  { type: "dare", content: "背著右邊的人繞房間一圈。", level: "Normal" },
  { type: "dare", content: "用屁股在空中寫數字「8」。", level: "Normal" },
  { type: "dare", content: "模仿在場某人的笑聲。", level: "Normal" },
  {
    type: "dare",
    content: "讓右邊的人幫你整理頭髮（或摸頭）。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "對著手機鏡頭深情告白（對象隨意）。",
    level: "Normal",
  },
  { type: "dare", content: "唱一首兒歌的副歌。", level: "Normal" },
  { type: "dare", content: "用非慣用手寫下自己的名字。", level: "Normal" },
  { type: "dare", content: "模仿殭屍跳三下。", level: "Normal" },
  { type: "dare", content: "讓大家看你錢包裡有多少錢。", level: "Normal" },
  { type: "dare", content: "隨機念出手機裡的一條簡訊內容。", level: "Normal" },
  { type: "dare", content: "模仿新聞主播播報氣象。", level: "Normal" },
  { type: "dare", content: "聞右邊人的襪子。", level: "Normal" },
  { type: "dare", content: "讓左邊的人畫你的臉。", level: "Normal" },
  { type: "dare", content: "跟在場一位異性十指緊扣一分鐘。", level: "Normal" },
  { type: "dare", content: "跳一段性感的舞蹈。", level: "Normal" },
  { type: "dare", content: "親吻右邊人的手背。", level: "Normal" },
  {
    type: "dare",
    content: "讓大家看你手機裡最近的一張自拍。",
    level: "Normal",
  },
  { type: "dare", content: "跟左邊的人對視30秒不能笑。", level: "Normal" },
  { type: "dare", content: "大聲朗讀手機裡最新的一則訊息。", level: "Normal" },
  { type: "dare", content: "用屁股撞擊在場所有人的屁股。", level: "Normal" },
];
