const QUESTIONS_NORMAL = [
  { type: "truth", content: "初吻是在幾歲？", level: "Normal" },
  {
    type: "truth",
    content: "曾經對父母說過最大的一個謊是什麼？",
    level: "Normal",
  },
  { type: "truth", content: "上一次哭是什麼時候？為什麼？", level: "Normal" },
  { type: "truth", content: "手機裡最後一張照片是什麼？", level: "Normal" },
  {
    type: "truth",
    content: "如果可以回到過去，你想回到哪個時刻？",
    level: "Normal",
  },
  { type: "truth", content: "你覺得男女之間有純友誼嗎？", level: "Normal" },
  { type: "truth", content: "曾經被劈腿過嗎？", level: "Normal" },
  { type: "truth", content: "你做過最丟臉的一件事是什麼？", level: "Normal" },
  {
    type: "truth",
    content: "身上最敏感（怕癢）的部位是哪裡？",
    level: "Normal",
  },
  { type: "truth", content: "有沒有暗戀過朋友的另一半？", level: "Normal" },
  { type: "truth", content: "曾經偷看過另一半的手機嗎？", level: "Normal" },
  { type: "truth", content: "覺得自己長得好看嗎？", level: "Normal" },
  { type: "truth", content: "交過幾任男/女朋友？", level: "Normal" },
  {
    type: "truth",
    content: "你會在意另一半的收入比你高/低嗎？",
    level: "Normal",
  },
  { type: "truth", content: "最近一次跟人吵架是為了什麼？", level: "Normal" },
  { type: "truth", content: "你覺得自己最大的缺點是什麼？", level: "Normal" },
  { type: "truth", content: "曾經為了愛情放棄過什麼嗎？", level: "Normal" },
  { type: "truth", content: "願意跟前任當朋友嗎？", level: "Normal" },
  { type: "truth", content: "目前有喜歡的人嗎？", level: "Normal" },
  { type: "truth", content: "曾經在電梯裡放屁並假裝沒事嗎？", level: "Normal" },
  {
    type: "truth",
    content: "你最想整型的部位是哪裡（如果不整型選一個最不滿意的）？",
    level: "Normal",
  },
  {
    type: "truth",
    content: "如果明天是世界末日，你今晚想跟誰過？",
    level: "Normal",
  },
  { type: "truth", content: "曾經裝病請假過嗎？", level: "Normal" },
  { type: "truth", content: "你覺得在場誰最有趣？", level: "Normal" },
  {
    type: "truth",
    content: "如果可以跟在場的一個人交換人生，你會選誰？",
    level: "Normal",
  },
  { type: "truth", content: "喝醉後做過最瘋狂的事？", level: "Normal" },
  { type: "truth", content: "你最討厭異性什麼樣的行為？", level: "Normal" },
  { type: "truth", content: "曾經被同性告白過嗎？", level: "Normal" },
  { type: "truth", content: "你相信一見鍾情嗎？", level: "Normal" },
  { type: "truth", content: "為了討好別人做過最蠢的事？", level: "Normal" },
  { type: "truth", content: "曾經在網路上當過酸民嗎？", level: "Normal" },
  { type: "truth", content: "覺得結婚重要嗎？", level: "Normal" },
  { type: "truth", content: "有沒有被老師或老闆罵哭過？", level: "Normal" },
  { type: "truth", content: "曾經借錢不還（或忘記還）嗎？", level: "Normal" },
  { type: "truth", content: "你覺得自己花心還是專情？", level: "Normal" },
  { type: "truth", content: "會為了朋友背叛另一半嗎？", level: "Normal" },
  { type: "truth", content: "曾經後悔跟某人分手嗎？", level: "Normal" },
  { type: "truth", content: "你的夢中情人標準是什麼？", level: "Normal" },
  { type: "truth", content: "會介意另一半整型嗎？", level: "Normal" },
  { type: "truth", content: "曾經在游泳池裡偷尿尿嗎？", level: "Normal" },
  {
    type: "truth",
    content: "覺得自己在朋友圈裡扮演什麼角色？",
    level: "Normal",
  },
  { type: "truth", content: "曾經因為長相自卑過嗎？", level: "Normal" },
  { type: "truth", content: "收到過最爛的禮物是什麼？", level: "Normal" },
  { type: "truth", content: "你最不能接受的食物是什麼？", level: "Normal" },
  { type: "truth", content: "曾經跟好朋友喜歡上同一個人嗎？", level: "Normal" },
  { type: "truth", content: "覺得這裡誰最會穿搭？", level: "Normal" },
  { type: "truth", content: "敢不敢現在公開你的瀏覽器紀錄？", level: "Normal" },
  { type: "truth", content: "曾經偷拿過別人的東西嗎？", level: "Normal" },
  { type: "truth", content: "最近一個搜尋的關鍵字是什麼？", level: "Normal" },
  { type: "truth", content: "曾經假裝生病請假去做什麼？", level: "Normal" },
  { type: "truth", content: "覺得在場誰的衣品最差？", level: "Normal" },
  {
    type: "truth",
    content: "手機裡最醜的一張照片是誰？（必須展示）",
    level: "Normal",
  },
  { type: "truth", content: "曾經偷看過誰的手機或日記？", level: "Normal" },
  { type: "truth", content: "說出你在場最想吐槽的一個人。", level: "Normal" },
  {
    type: "truth",
    content: "在場這群人中，你覺得誰將來會最富有？",
    level: "Normal",
  },
  {
    type: "truth",
    content: "如果你是異性，你會想跟自己交往嗎？",
    level: "Normal",
  },
  { type: "truth", content: "曾經把別人送的禮物轉送出去嗎？", level: "Normal" },
  { type: "truth", content: "覺得在場誰最容易被詐騙？", level: "Normal" },
  {
    type: "truth",
    content: "說出一個你不想讓父母知道的秘密。",
    level: "Normal",
  },
  { type: "truth", content: "曾經在公共場合做過最丟臉的事？", level: "Normal" },
  { type: "truth", content: "覺得哪個卡通人物最性感？", level: "Normal" },
  {
    type: "truth",
    content: "如果要刪除一位在場好友的聯絡方式，選誰？",
    level: "Normal",
  },
  { type: "truth", content: "曾經對老闆或老師說過最大的謊？", level: "Normal" },
  { type: "truth", content: "洗衣服會把內褲跟襪子一起洗嗎？", level: "Normal" },
  { type: "truth", content: "曾經偷吃過別人的東西沒承認嗎？", level: "Normal" },
  { type: "truth", content: "覺得在場誰最會記仇？", level: "Normal" },
  { type: "truth", content: "有沒有挖鼻孔吃下去過？", level: "Normal" },
  { type: "truth", content: "學生時代曾經作弊過嗎？", level: "Normal" },
  { type: "truth", content: "上一次生氣是因為什麼事情？", level: "Normal" },
  { type: "truth", content: "覺得自己最大的優點是什麼？", level: "Normal" },
  { type: "truth", content: "曾經對好朋友說過謊嗎？", level: "Normal" },
  { type: "truth", content: "有沒有暗戀過老師或長輩？", level: "Normal" },
  { type: "truth", content: "第一次約會去了哪裡？", level: "Normal" },
  { type: "truth", content: "最討厭的一種食物是什麼？", level: "Normal" },
  {
    type: "truth",
    content: "曾經在電影院看電影看到睡著過嗎？",
    level: "Normal",
  },
  { type: "truth", content: "敢不敢一個人看恐怖片？", level: "Normal" },
  { type: "truth", content: "曾經迷路過最久的一次是多久？", level: "Normal" },
  { type: "truth", content: "小時候最怕什麼東西？", level: "Normal" },
  {
    type: "truth",
    content: "曾經不小心把別人的秘密說出去嗎？",
    level: "Normal",
  },
  { type: "truth", content: "覺得在場誰最幽默好笑？", level: "Normal" },
  { type: "truth", content: "如果能回到過去，最想回到幾歲？", level: "Normal" },
  { type: "truth", content: "如果可以整型，你最想整哪裡？", level: "Normal" },
  {
    type: "truth",
    content: "你覺得在場誰最適合當你的另一半？",
    level: "Normal",
  },
  { type: "truth", content: "有沒有欠錢不還過？", level: "Normal" },
  { type: "truth", content: "最想刪除的一張照片是什麼？", level: "Normal" },
  { type: "truth", content: "說出一個你討厭的藝人。", level: "Normal" },
  { type: "truth", content: "最尷尬的一次約會經驗？", level: "Normal" },
  { type: "truth", content: "覺得自己哪個部位最性感？", level: "Normal" },
  {
    type: "truth",
    content: "如果中了一億，會分給在場的人嗎？",
    level: "Normal",
  },
  { type: "truth", content: "最受不了異性哪個行為？", level: "Normal" },
  { type: "truth", content: "曾經在夢裡夢過在場的人嗎？", level: "Normal" },
  { type: "truth", content: "有沒有說過謊來逃避聚會？", level: "Normal" },
  { type: "truth", content: "有沒有什麼怪癖？", level: "Normal" },
  { type: "truth", content: "曾經被警察攔下來過嗎？", level: "Normal" },
  { type: "truth", content: "覺得在場誰最單純？", level: "Normal" },
  { type: "truth", content: "曾經偷拿過家裡的錢嗎？", level: "Normal" },
  { type: "truth", content: "覺得自己的顏值幾分？", level: "Normal" },
  { type: "truth", content: "洗澡會順便尿尿嗎？", level: "Normal" },
  { type: "truth", content: "曾經裸睡過嗎？", level: "Normal" },
  { type: "dare", content: "讓左邊的人幫你整理頭髮。", level: "Normal" },
  { type: "dare", content: "和右邊的人十指緊扣 10 秒。", level: "Normal" },
  { type: "dare", content: "對著鏡子猜拳直到贏為止。", level: "Normal" },
  { type: "dare", content: "跟左邊的人十指緊扣 10 秒。", level: "Normal" },
  {
    type: "dare",
    content: "隨機打給通訊錄一個人唱生日快樂歌。",
    level: "Normal",
  },
  { type: "dare", content: "含著水哼一首歌讓大家猜。", level: "Normal" },
  { type: "dare", content: "跳一段目前最紅的抖音舞。", level: "Normal" },
  {
    type: "dare",
    content: "讓右邊的人搔你癢 10 秒鐘，不能笑。",
    level: "Normal",
  },
  { type: "dare", content: "用你的手肘打字發一則動態。", level: "Normal" },
  { type: "dare", content: "跪在椅子上模仿古代人請安。", level: "Normal" },
  { type: "dare", content: "夾著鼻子說話一輪。", level: "Normal" },
  {
    type: "dare",
    content: "把鞋子脫下來，聞一下並形容味道。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "去廚房特調一杯「怪味飲料」並喝一口。",
    level: "Normal",
  },

  { type: "dare", content: "假裝電視購物推銷你穿的襪子。", level: "Normal" },
  { type: "dare", content: "對著Siri大喊「我好寂寞」。", level: "Normal" },
  { type: "dare", content: "背著右邊的人繞房間一圈。", level: "Normal" },
  { type: "dare", content: "模仿在場某人的笑聲。", level: "Normal" },
  {
    type: "dare",
    content: "對著手機鏡頭深情告白（對象隨意）。",
    level: "Normal",
  },
  { type: "dare", content: "讓大家看你錢包裡有多少錢。", level: "Normal" },
  { type: "dare", content: "隨機念出手機裡的一條簡訊內容。", level: "Normal" },
  { type: "dare", content: "讓左邊的人畫你的臉。", level: "Normal" },
  { type: "dare", content: "跳一段性感的舞蹈。", level: "Normal" },
  {
    type: "dare",
    content: "在 IG 限時動態發一張全黑圖，並寫「我好難過」。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "讓在場的一個人用口紅在你臉上畫畫。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "隨機挑一位朋友傳語音訊息說「我愛你」。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "公主抱（或被公主抱）在場的一個人深蹲 3 下。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "打給前男/女友（或喜歡的人）響一聲掛斷。",
    level: "Normal",
  },
  { type: "dare", content: "讓大家挑一張你的醜照發到群組。", level: "Normal" },
  { type: "dare", content: "模仿大猩猩搥胸並大吼。", level: "Normal" },
  {
    type: "dare",
    content: "含著一口水，聽別人講笑話不准噴出來。",
    level: "Normal",
  },
  { type: "dare", content: "對在場的一個人撒嬌一分鐘。", level: "Normal" },

  { type: "dare", content: "選一個人，深情地聞他的脖子。", level: "Normal" },
  { type: "dare", content: "跪在地上跟在場的一個人求婚。", level: "Normal" },
  {
    type: "dare",
    content: "讓大家看你手機相簿裡的第 10 張照片。",
    level: "Normal",
  },
  { type: "dare", content: "用下巴夾住手機傳訊息給一個人。", level: "Normal" },

  { type: "dare", content: "大聲朗讀你最近的一則曖昧訊息。", level: "Normal" },
  {
    type: "dare",
    content: "讓大家幫你塗指甲油（男生也要）。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "用舌頭舔自己的鼻尖（舔不到也要試）。",
    level: "Normal",
  },
  { type: "dare", content: "模仿鋼管舞女郎繞著某人跳舞。", level: "Normal" },
  {
    type: "dare",
    content: "讓某人把手伸進你的衣服裡暖手（背部）。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "隨機傳一張自拍給通訊錄第 5 個人。",
    level: "Normal",
  },
  {
    type: "dare",
    content: "讓在場的人決定你 Line 的狀態消息，維持一天。",
    level: "Normal",
  },
  { type: "dare", content: "被在場的人壁咚並深情對視。", level: "Normal" },
  { type: "dare", content: "趴在地上學狗爬，並叫兩聲。", level: "Normal" },
  { type: "dare", content: "讓大家看你的蝦皮/購物車內容。", level: "Normal" },
  {
    type: "dare",
    content: "跟隔壁的人交換上衣穿（如果是同性）。",
    level: "Normal",
  },
  { type: "dare", content: "用曖昧的語氣念出產品說明書。", level: "Normal" },
  { type: "dare", content: "模仿 AV 女優/男優的開場白。", level: "Normal" },
  { type: "dare", content: "對著牆壁深蹲持續一分鐘。", level: "Normal" },
  {
    type: "dare",
    content: "喝一杯啤酒（或飲料）不能用手拿。",
    level: "Normal",
  },
  { type: "dare", content: "把冰塊含在嘴裡直到融化。", level: "Normal" },
  { type: "dare", content: "讓某人用馬克筆在你手臂上簽名。", level: "Normal" },
];
