const QUESTIONS_ADULT = [
  {
    type: "truth",
    content: "在場的異性中，誰最接近你的性幻想對象？",
    level: "Adult",
  },
  { type: "truth", content: "第一次發生性行為是在幾歲？", level: "Adult" },
  {
    type: "truth",
    content: "曾經有過一夜情嗎？或者想嘗試嗎？",
    level: "Adult",
  },
  { type: "truth", content: "能夠接受的年齡差最大是多少？", level: "Adult" },
  { type: "truth", content: "喜歡開燈還是關燈辦事？", level: "Adult" },
  { type: "truth", content: "喜歡什麼體位？", level: "Adult" },
  { type: "truth", content: "曾經在公共場所做過嗎？", level: "Adult" },
  { type: "truth", content: "最喜歡身體哪個部位被觸摸？", level: "Adult" },
  { type: "truth", content: "曾經幻想過跟在場誰發生關係？", level: "Adult" },
  { type: "truth", content: "接受一夜情嗎？", level: "Adult" },
  {
    type: "truth",
    content: "曾經有過性幻想對象是老師或上司嗎？",
    level: "Adult",
  },
  { type: "truth", content: "喜歡粗暴一點還是溫柔一點？", level: "Adult" },
  { type: "truth", content: "曾經使用過情趣玩具嗎？", level: "Adult" },
  { type: "truth", content: "覺得尺寸重要嗎？", level: "Adult" },
  { type: "truth", content: "曾經在做的時候睡著嗎？", level: "Adult" },
  { type: "truth", content: "喜歡口交嗎？", level: "Adult" },
  { type: "truth", content: "曾經被抓包過自慰嗎？", level: "Adult" },
  { type: "truth", content: "喜歡被綁起來嗎？", level: "Adult" },
  { type: "truth", content: "曾經玩過角色扮演嗎？", level: "Adult" },
  { type: "truth", content: "覺得性愛中最重要的環節是什麼？", level: "Adult" },
  {
    type: "truth",
    content: "你覺得自己性能力如何（1-10分）？",
    level: "Adult",
  },
  { type: "truth", content: "最近一次DIY是什麼時候？", level: "Adult" },
  { type: "truth", content: "看過最奇怪的A片類型是什麼？", level: "Adult" },
  { type: "truth", content: "覺得性重要還是愛重要？", level: "Adult" },
  { type: "truth", content: "喜歡被控制還是控制對方？", level: "Adult" },
  { type: "truth", content: "有沒有假裝高潮過？", level: "Adult" },
  { type: "truth", content: "最喜歡的愛愛時間長度？", level: "Adult" },
  { type: "truth", content: "曾經在車上做過嗎？", level: "Adult" },
  { type: "truth", content: "喜歡穿丁字褲嗎？", level: "Adult" },
  { type: "truth", content: "有沒有拍過私密照？", level: "Adult" },
  { type: "truth", content: "曾經跟網友約炮過嗎？", level: "Adult" },
  { type: "dare", content: "親吻你左邊玩家的脖子。", level: "Adult" },
  {
    type: "dare",
    content: "選一位異性，用嘴對嘴傳遞一張衛生紙（或冰塊）。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "在在場異性中選一位，在他耳邊吹氣並說悄悄話。",
    level: "Adult",
  },
  { type: "dare", content: "讓一位異性坐在你大腿上 1 分鐘。", level: "Adult" },
  {
    type: "dare",
    content: "對著一位異性做出挑逗的吃香蕉（或手指）動作。",
    level: "Adult",
  },
  {
    type: "dare",
    content: "讓右邊的人在你脖子上種草莓（或假裝用力吸一下）。",
    level: "Adult",
  },
  { type: "dare", content: "發出呻吟聲10秒。", level: "Adult" },
  { type: "dare", content: "對著在場一位異性做出挑逗動作。", level: "Adult" },
  { type: "dare", content: "讓在場一位異性摸你的大腿內側。", level: "Adult" },
  { type: "dare", content: "模仿一種性愛姿勢（對著空氣）。", level: "Adult" },
  { type: "dare", content: "脫掉一件衣服（外套或配件）。", level: "Adult" },
  { type: "dare", content: "親吻在場一位異性的耳朵。", level: "Adult" },
  {
    type: "dare",
    content: "讓在場一位異性坐在你身上做伏地挺身。",
    level: "Adult",
  },
  { type: "dare", content: "用嘴巴解開在場一位異性的扣子。", level: "Adult" },
  {
    type: "dare",
    content: "隔著衣服撫摸在場一位異性的胸部/腹肌。",
    level: "Adult",
  },
  { type: "dare", content: "說一句你覺得最色的話。", level: "Adult" },
  { type: "dare", content: "發出曖昧的聲音10秒。", level: "Adult" },
  { type: "dare", content: "模仿高潮的叫聲。", level: "Adult" },
  { type: "dare", content: "對著異性做頂胯動作10下。", level: "Adult" },
  { type: "dare", content: "讓異性摸你的腹肌/肚子。", level: "Adult" },
  { type: "dare", content: "親吻異性的鎖骨。", level: "Adult" },
  { type: "dare", content: "用嘴巴解開異性的一顆扣子。", level: "Adult" },
  { type: "dare", content: "在異性耳邊吹氣。", level: "Adult" },
  { type: "dare", content: "讓異性坐在你大腿上30秒。", level: "Adult" },
  { type: "dare", content: "隔著衣服親吻異性的胸口。", level: "Adult" },
  { type: "dare", content: "表演吃香蕉（或是手指）。", level: "Adult" },
  { type: "dare", content: "讓異性幫你脫襪子。", level: "Adult" },
  { type: "dare", content: "用嘴巴餵異性吃東西。", level: "Adult" },
  { type: "dare", content: "躺在地上讓異性跨過去。", level: "Adult" },
  { type: "dare", content: "模仿AV女優/男優的經典台詞。", level: "Adult" },
  { type: "dare", content: "讓異性打你的屁股一下。", level: "Adult" },
  { type: "dare", content: "握住異性的手放在自己胸口。", level: "Adult" },
  { type: "dare", content: "跟異性磨鼻子10秒。", level: "Adult" },
  { type: "dare", content: "用很色的語氣說「我要吃掉你」。", level: "Adult" },
  { type: "dare", content: "讓異性檢查你的內衣/內褲顏色。", level: "Adult" },
  { type: "dare", content: "對著異性跳M字腿。", level: "Adult" },
  { type: "dare", content: "含著冰塊親吻異性的手。", level: "Adult" },
  { type: "dare", content: "讓異性聞你的脖子。", level: "Adult" },
  { type: "dare", content: "用領帶或皮帶輕輕綁住異性的手。", level: "Adult" },
];
