const QUESTIONS_HARD = [
  { type: "truth", content: "說出你做過最違法的事情。", level: "Hard" },
  { type: "truth", content: "這輩子最後悔的一件事是什麼？", level: "Hard" },
  {
    type: "truth",
    content: "如果生命只剩24小時，想對誰說什麼？",
    level: "Hard",
  },
  {
    type: "truth",
    content: "成長過程中，哪件事對你的價值觀影響最大？",
    level: "Hard",
  },
  { type: "truth", content: "你最害怕失去什麼？", level: "Hard" },
  { type: "truth", content: "曾經對朋友的另一半動過心嗎？", level: "Hard" },
  { type: "truth", content: "覺得在場誰最難相處？", level: "Hard" },
  {
    type: "truth",
    content: "如果必須跟在場一個人絕交，你會選誰？",
    level: "Hard",
  },
  { type: "truth", content: "上一次發自內心大哭是什麼時候？", level: "Hard" },
  { type: "truth", content: "你覺得自己最大的缺點是什麼？", level: "Hard" },
  { type: "truth", content: "有沒有哪個夢想是你已經放棄的？", level: "Hard" },
  { type: "truth", content: "曾經背叛過好朋友嗎？", level: "Hard" },
  { type: "truth", content: "說出一個你從未告訴過別人的秘密。", level: "Hard" },
  { type: "truth", content: "曾經偷過東西嗎（不論大小）？", level: "Hard" },
  { type: "truth", content: "對在場誰的第一印象最差？", level: "Hard" },
  { type: "truth", content: "曾經想過要整型嗎？想整哪裡？", level: "Hard" },
  { type: "truth", content: "覺得自己人生中最失敗的一件事？", level: "Hard" },
  { type: "truth", content: "曾經腳踏兩條船嗎？", level: "Hard" },
  {
    type: "truth",
    content: "討厭在場某人的某個行為嗎？請誠實。",
    level: "Hard",
  },
  { type: "truth", content: "曾經偷看過另一半的手機訊息嗎？", level: "Hard" },
  {
    type: "truth",
    content: "如果必須殺死一個人才能救自己，你會選誰（假設情境）？",
    level: "Hard",
  },
  { type: "truth", content: "曾經後悔跟某任交往嗎？", level: "Hard" },
  { type: "truth", content: "覺得自己是不是一個好人？", level: "Hard" },
  { type: "truth", content: "曾經為了利益出賣過朋友嗎？", level: "Hard" },
  { type: "truth", content: "說出一個你最想刪除的黑歷史。", level: "Hard" },
  { type: "truth", content: "曾經在背後說過在場誰的壞話？", level: "Hard" },
  { type: "truth", content: "曾經被劈腿過嗎？", level: "Hard" },
  {
    type: "truth",
    content: "如果一定要跟在場一個人接吻，你會選誰？",
    level: "Hard",
  },
  { type: "truth", content: "曾經在心裡偷偷詛咒過誰？", level: "Hard" },
  { type: "truth", content: "你覺得在場誰最虛偽？", level: "Hard" },
  { type: "truth", content: "曾經對朋友的男/女朋友動心過嗎？", level: "Hard" },
  { type: "truth", content: "有沒有偷看過伴侶的手機？", level: "Hard" },
  { type: "truth", content: "曾經跟不喜歡的人交往過嗎？", level: "Hard" },
  { type: "truth", content: "曾經為了愛做過最傻的事？", level: "Hard" },
  { type: "truth", content: "有沒有當過第三者（或被當過）？", level: "Hard" },
  {
    type: "truth",
    content: "如果世界末日，只能救一個人，救誰？",
    level: "Hard",
  },
  { type: "truth", content: "最想跟誰道歉？", level: "Hard" },
  { type: "truth", content: "最害怕的一種死法？", level: "Hard" },
  {
    type: "dare",
    content: "讓大家瀏覽你的瀏覽器搜尋紀錄（最近3條）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "去冰箱拿一顆冰塊，放在衣服裡直到融化。",
    level: "Hard",
  },
  { type: "dare", content: "在一位異性身上做伏地挺身 5 下。", level: "Hard" },
  {
    type: "dare",
    content: "讓大家看你手機相簿裡最新的那張截圖。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "跟大家分享你內褲的顏色和款式（必須檢查）。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "公主抱（或被公主抱）一位異性做深蹲 3 下。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "擁抱在你右邊的人 20 秒，什麼話都不能說。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "打電話給一位好久沒聯絡的朋友，說想他了。",
    level: "Hard",
  },
  { type: "dare", content: "選一個人，幫他按摩 3 分鐘。", level: "Hard" },
  {
    type: "dare",
    content: "在社群媒體上發一篇感謝文，感謝在場的一個人。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "打電話給前任（或隨機異性朋友）說「我好想你」。",
    level: "Hard",
  },
  { type: "dare", content: "讓左邊的人在你的臉上畫一個圖案。", level: "Hard" },
  {
    type: "dare",
    content: "隨機挑選通訊錄的一個人，傳送「我懷孕了/我讓別人懷孕了」。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "讓大家看你手機瀏覽器紀錄的最後一頁。",
    level: "Hard",
  },
  {
    type: "dare",
    content: "模仿一種猥瑣的表情自拍並發到群組。",
    level: "Hard",
  },
  { type: "dare", content: "跪在地上向在場的一個人求婚。", level: "Hard" },
  { type: "dare", content: "讓右邊的人聞你的腋下。", level: "Hard" },
  { type: "dare", content: "喝一杯特調飲料（大家隨意加料）。", level: "Hard" },
  { type: "dare", content: "大聲喊出自己最丟臉的綽號。", level: "Hard" },
  { type: "dare", content: "模仿高潮的表情10秒。", level: "Hard" },
  { type: "dare", content: "公主抱在場一位異性。", level: "Hard" },
  { type: "dare", content: "伏地挺身10下（可以在人身上）。", level: "Hard" },
  { type: "dare", content: "用嘴巴咬下左邊人身上的便利貼。", level: "Hard" },
  { type: "dare", content: "喝一杯加了鹽的可樂。", level: "Hard" },
  { type: "dare", content: "讓右邊的人坐在你背上做伏地挺身。", level: "Hard" },
  { type: "dare", content: "把頭像換成鬼臉照一天。", level: "Hard" },
  {
    type: "dare",
    content: "傳訊息給第10個聯絡人說「借我錢」。",
    level: "Hard",
  },
];
