const QUESTIONS_EASY = [
  { type: "truth", content: "你的手機桌布是什麼圖片？", level: "Easy" },
  {
    type: "truth",
    content: "如果只能吃一種食物一輩子，你會選什麼？",
    level: "Easy",
  },
  { type: "truth", content: "比較喜歡貓還是狗？", level: "Easy" },
  {
    type: "truth",
    content: "睡覺時有什麼怪癖嗎（例如一定要抱枕頭）？",
    level: "Easy",
  },
  { type: "truth", content: "上一次大笑是因為什麼事情？", level: "Easy" },
  { type: "truth", content: "你最喜歡的季節是哪一個？", level: "Easy" },
  { type: "truth", content: "你最害怕的動物或昆蟲是什麼？", level: "Easy" },
  { type: "truth", content: "去KTV必點的一首歌是？", level: "Easy" },
  { type: "truth", content: "洗澡時會唱歌嗎？", level: "Easy" },
  { type: "truth", content: "你覺得自己像哪一種動物？", level: "Easy" },
  { type: "truth", content: "有沒有綽號？是怎麼來的？", level: "Easy" },
  { type: "truth", content: "早餐通常都吃什麼？", level: "Easy" },
  { type: "truth", content: "放假最喜歡做的事情是什麼？", level: "Easy" },
  { type: "truth", content: "比較喜歡傳訊息還是講電話？", level: "Easy" },
  { type: "truth", content: "你最拿手的料理是什麼？", level: "Easy" },
  { type: "truth", content: "有沒有近視？幾度？", level: "Easy" },
  {
    type: "truth",
    content: "如果中樂透頭獎，第一件事會做什麼？",
    level: "Easy",
  },
  { type: "truth", content: "你相信世界上有鬼嗎？", level: "Easy" },
  { type: "truth", content: "比較喜歡夏天還是冬天？", level: "Easy" },
  { type: "truth", content: "你最喜歡的電影是哪一部？", level: "Easy" },
  { type: "truth", content: "買東西會不會殺價？", level: "Easy" },
  { type: "truth", content: "喜歡喝咖啡還是茶？", level: "Easy" },
  { type: "truth", content: "最近在追的一部劇？", level: "Easy" },
  { type: "truth", content: "你有潔癖嗎？", level: "Easy" },
  { type: "truth", content: "生氣的時候會怎麼發洩？", level: "Easy" },
  { type: "truth", content: "你最喜歡的顏色？", level: "Easy" },
  { type: "truth", content: "敢不敢吃香菜？", level: "Easy" },
  { type: "truth", content: "曾經養過什麼寵物？", level: "Easy" },
  { type: "truth", content: "小時候的夢想職業是什麼？", level: "Easy" },
  {
    type: "truth",
    content: "最受不了別人做什麼小動作（例如抖腳）？",
    level: "Easy",
  },
  { type: "truth", content: "睡覺會打呼嗎？", level: "Easy" },
  { type: "truth", content: "比較喜歡室內活動還是戶外活動？", level: "Easy" },
  { type: "truth", content: "去便利商店必買的東西？", level: "Easy" },
  { type: "truth", content: "你會看星座運勢嗎？", level: "Easy" },
  { type: "truth", content: "身上有任何胎記嗎？", level: "Easy" },
  {
    type: "truth",
    content: "喜歡穿裙子還是褲子（或西裝還是休閒服）？",
    level: "Easy",
  },
  { type: "truth", content: "吃火鍋必加的料是什麼？", level: "Easy" },
  { type: "truth", content: "你最想去的國家是哪裡？", level: "Easy" },
  { type: "truth", content: "會不會游泳？", level: "Easy" },
  { type: "truth", content: "敢不敢坐雲霄飛車？", level: "Easy" },
  { type: "truth", content: "一天通常滑手機多久？", level: "Easy" },
  { type: "truth", content: "喜歡聽什麼類型的音樂？", level: "Easy" },
  { type: "truth", content: "覺得自己脾氣好嗎？", level: "Easy" },
  { type: "truth", content: "有沒有偶像？", level: "Easy" },
  { type: "truth", content: "喜歡吃甜食還是鹹食？", level: "Easy" },
  { type: "truth", content: "睡覺一定要關燈嗎？", level: "Easy" },
  { type: "truth", content: "你最喜歡的身材部位是哪裡？", level: "Easy" },
  { type: "truth", content: "曾經在公共場合跌倒過嗎？", level: "Easy" },
  { type: "truth", content: "喜歡熱鬧還是安靜？", level: "Easy" },
  { type: "truth", content: "現在肚子餓不餓？", level: "Easy" },
  {
    type: "truth",
    content: "如果能有超能力，你想要什麼？",
    level: "Easy",
  },
  { type: "truth", content: "洗澡時會做的最奇怪的一件事？", level: "Easy" },
  { type: "truth", content: "說出一個你絕對不敢吃的食物。", level: "Easy" },
  { type: "truth", content: "你覺得在場誰最自戀？", level: "Easy" },
  { type: "truth", content: "上一次尿床是幾歲？", level: "Easy" },
  { type: "truth", content: "買過最後悔的東西是什麼？", level: "Easy" },
  { type: "truth", content: "如果明天是世界末日，你會吃什麼？", level: "Easy" },
  { type: "truth", content: "做過最奇怪的夢是什麼？", level: "Easy" },
  { type: "truth", content: "覺得自己心理年齡幾歲？", level: "Easy" },
  {
    type: "truth",
    content: "如果可以跟在場一人交換身份一天，想選誰？",
    level: "Easy",
  },
  { type: "truth", content: "說出一件你小時候做過的蠢事。", level: "Easy" },
  { type: "truth", content: "你有多少天沒洗頭的最高紀錄？", level: "Easy" },
  { type: "truth", content: "覺得在場誰看起來脾氣最好？", level: "Easy" },
  { type: "truth", content: "最近看的一本書或漫畫是什麼？", level: "Easy" },
  { type: "truth", content: "你相信星座或算命嗎？", level: "Easy" },
  { type: "truth", content: "如果可以出國，現在最想去哪裡？", level: "Easy" },
  { type: "truth", content: "假日通常喜歡做什麼休閒活動？", level: "Easy" },
  { type: "truth", content: "有沒有收集什麼特別的東西？", level: "Easy" },
  { type: "truth", content: "最喜歡的水果是什麼？", level: "Easy" },
  { type: "truth", content: "喜歡爬山還是去海邊？", level: "Easy" },
  { type: "truth", content: "敢不敢吃榴槤或臭豆腐？", level: "Easy" },
  { type: "truth", content: "最近一次去便利商店買了什麼？", level: "Easy" },
  { type: "truth", content: "上廁所完會看一眼排泄物嗎？", level: "Easy" },
  { type: "truth", content: "如果變成異性，第一件事想做什麼？", level: "Easy" },
  { type: "truth", content: "覺得自己聰明嗎？", level: "Easy" },
  { type: "truth", content: "最喜歡的一道菜？", level: "Easy" },
  { type: "dare", content: "模仿一種動物直到下一輪。", level: "Easy" },
  { type: "dare", content: "做鬼臉自拍一張。", level: "Easy" },
  { type: "dare", content: "模仿一種動物的叫聲。", level: "Easy" },
  { type: "dare", content: "對著窗外大喊：「我是笨蛋！」", level: "Easy" },
  { type: "dare", content: "原地轉 10 圈，然後走直線。", level: "Easy" },
  { type: "dare", content: "讓大家看你手機裡第 5 張照片。", level: "Easy" },
  { type: "dare", content: "用「喵」代替「我」說話三分鐘。", level: "Easy" },
  { type: "dare", content: "模仿在場某個人的口頭禪。", level: "Easy" },
  { type: "dare", content: "誇獎右邊的人三個優點。", level: "Easy" },
  { type: "dare", content: "唱一首兒歌（例如兩隻老虎）。", level: "Easy" },
  { type: "dare", content: "用屁股寫字（你的名字）。", level: "Easy" },
  { type: "dare", content: "雙手舉高維持一分鐘。", level: "Easy" },
  { type: "dare", content: "模仿名模走台步一圈。", level: "Easy" },
  { type: "dare", content: "講一個冷笑話。", level: "Easy" },
  { type: "dare", content: "跟大家分享你最近的一個搜尋紀錄。", level: "Easy" },
  { type: "dare", content: "對著鏡子稱讚自己 30 秒。", level: "Easy" },
  { type: "dare", content: "學嬰兒哭 10 秒。", level: "Easy" },
  { type: "dare", content: "喝一大杯水。", level: "Easy" },
  { type: "dare", content: "讓大家檢查你的包包。", level: "Easy" },
  { type: "dare", content: "做一個最醜的鬼臉。", level: "Easy" },
  { type: "dare", content: "模仿貓叫三聲「喵喵喵」。", level: "Easy" },
  { type: "dare", content: "站起來原地轉一圈。", level: "Easy" },
  { type: "dare", content: "跟左邊的人擊掌。", level: "Easy" },
  { type: "dare", content: "說一個笑話（不好笑也要笑）。", level: "Easy" },
  { type: "dare", content: "閉眼單腳站立5秒。", level: "Easy" },
  { type: "dare", content: "模仿機器人說話一句。", level: "Easy" },
  { type: "dare", content: "對著空氣揮手說「嗨」。", level: "Easy" },
  { type: "dare", content: "做出一個驚訝的表情維持5秒。", level: "Easy" },
  { type: "dare", content: "模仿一種樂器的聲音。", level: "Easy" },
  { type: "dare", content: "模仿一種動物的求偶舞。", level: "Easy" },
  { type: "dare", content: "用屁股寫「我愛你」。", level: "Easy" },
  { type: "dare", content: "讓在場的人幫你綁頭髮（或弄亂）。", level: "Easy" },
  { type: "dare", content: "跟牆壁深情告白30秒。", level: "Easy" },
  { type: "dare", content: "模仿便秘時的表情。", level: "Easy" },
  { type: "dare", content: "用舌頭舔手肘（舔不到也要試）。", level: "Easy" },
  {
    type: "dare",
    content: "用左手（非慣用手）寫下自己的名字。",
    level: "Easy",
  },
  { type: "dare", content: "學一聲貓叫或狗叫。", level: "Easy" },
  {
    type: "dare",
    content: "對坐在你右邊的人說「你是我的偶像」。",
    level: "Easy",
  },
  { type: "dare", content: "做 20 個深蹲。", level: "Easy" },
  { type: "dare", content: "讓坐在你左邊的人幫你抓頭髮造型。", level: "Easy" },
  { type: "dare", content: "模仿一種動物的走路方式繞場一周。", level: "Easy" },
  { type: "dare", content: "閉著眼睛畫一隻豬。", level: "Easy" },
  { type: "dare", content: "讓大家看你手機裡最新的一張照片。", level: "Easy" },
  { type: "dare", content: "跟空氣跳一隻舞持續 30 秒。", level: "Easy" },
  { type: "dare", content: "讓坐在對面的人彈你額頭一下。", level: "Easy" },
  {
    type: "dare",
    content: "擺一個時尚雜誌的 POSE 讓大家拍照。",
    level: "Easy",
  },
  { type: "dare", content: "念一段饒舌（隨便念什麼都可以）。", level: "Easy" },
  {
    type: "dare",
    content: "用奇怪的腔調講話直到下一輪輪到你。",
    level: "Easy",
  },
  { type: "dare", content: "閉氣 30 秒。", level: "Easy" },
  { type: "dare", content: "做 10 個伏地挺身。", level: "Easy" },
  { type: "dare", content: "對每個人露出一個職業假笑。", level: "Easy" },
  { type: "dare", content: "把鞋子脫掉直到下一輪結束。", level: "Easy" },
  { type: "dare", content: "模仿猴子抓癢。", level: "Easy" },
  { type: "dare", content: "鬥雞眼持續 10 秒。", level: "Easy" },
  { type: "dare", content: "用慢動作做任何事持續一分鐘。", level: "Easy" },
  { type: "dare", content: "讓大家看你的 Google 搜尋紀錄。", level: "Easy" },
  {
    type: "dare",
    content: "跟右手邊的人深情對視 10 秒不准笑。",
    level: "Easy",
  },
  { type: "dare", content: "把頭髮綁成沖天炮（或奇怪髮型）。", level: "Easy" },
  { type: "dare", content: "學新聞主播報導現在的狀況。", level: "Easy" },
  { type: "dare", content: "模仿殭屍跳。", level: "Easy" },
  { type: "dare", content: "用身體比出一個英文字母。", level: "Easy" },
  { type: "dare", content: "唱兩句你最喜歡的歌。", level: "Easy" },
  { type: "dare", content: "讓某人在你臉上貼一張便利貼。", level: "Easy" },
  { type: "dare", content: "用膝蓋走路繞桌子一圈。", level: "Easy" },
  { type: "dare", content: "模仿蠟筆小新的聲音說話。", level: "Easy" },
  { type: "dare", content: "躺在地板上 30 秒。", level: "Easy" },
  { type: "dare", content: "讓大家看你手機桌布。", level: "Easy" },

  { type: "dare", content: "把襪子脫下來套在手上。", level: "Easy" },
  { type: "dare", content: "對著窗外大喊「我好帥/美！」。", level: "Easy" },
  { type: "dare", content: "模仿喪屍吃人的樣子。", level: "Easy" },
  { type: "dare", content: "讓大家看你最近的一則 Line 訊息。", level: "Easy" },
];
